### ISSUE TITLE
Gem is missing dependency `gosu`

### ISSUE THREAD

**Issue by mhutter** [blowmage/rubyhop#2]
```
~ $ gem i rubyhop
Fetching: rubyhop-1.3.0.gem (100%)
Successfully installed rubyhop-1.3.0
1 gem installed
~ $ rubyhop
/Users/mhutter/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gosu (LoadError)
    from /Users/mhutter/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/mhutter/.rvm/gems/ruby-2.1.0@rubyhop/gems/rubyhop-1.3.0/lib/rubyhop.rb:1:in `<top (required)>'
    from /Users/mhutter/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/mhutter/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/mhutter/.rvm/gems/ruby-2.1.0@rubyhop/gems/rubyhop-1.3.0/bin/rubyhop:2:in `<top (required)>'
    from /Users/mhutter/.rvm/gems/ruby-2.1.0@rubyhop/bin/rubyhop:23:in `load'
    from /Users/mhutter/.rvm/gems/ruby-2.1.0@rubyhop/bin/rubyhop:23:in `<main>'
```

**Comment by blowmage** [comment]
Thanks for the heads up!
